version: "3.9"
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db
        env_file:
            - .env
        command: npm run start

    db:
      image: mysql:8.0
      cap_add:
        - SYS_NICE
      restart: always
      environment:
        - MYSQL_DATABASE=musicly
        - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
        - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
      

      ports:
        - '3306:3306'